server:
  port: 8080
cassandra:
 contactpoints: localhost,10.1.0.30
 port: 9042
 keyspace: assetmonitoring
 basepackages: 
kafka:
  bootstrap-servers: docker.for.mac.host.internal:30092
  groupid: assetconsumers
  topic:
    test: test.topic