apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: zookeeper
    name: green-zookeeper
    namespace: greencompute
spec:
    replicas: 1
    selector:
        matchLabels:
            app: zookeeper
    serviceName: greencompute-zookeeper-service
    updateStrategy:
        type: RollingUpdate
    podManagementPolicy: Parallel
    template:
        metadata:
          labels:
            app: zookeeper
        spec:
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      - labelSelector:
                          matchExpressions:
                            - key: "app"
                              operator: In
                              values:
                              - zookeeper
                        topologyKey: "kubernetes.io/hostname"
            containers:
            - name: greencompute-zookeeper
              image: "ibmcase/zookeeper:3.4.13"
              imagePullPolicy: Always
              ports:
              - containerPort: 2181
                name: client
                protocol: TCP
              - containerPort: 2888
                name: server
                protocol: TCP
              - containerPort: 3888
                name: leader-election
                protocol: TCP
              volumeMounts:
              - name: datadir
                mountPath: /opt/zookeeper/data
            securityContext:
                runAsUser: 1000
                fsGroup: 1000
    volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
