---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 9042
    nodePort: 32042
    name: cassandra
  - name: jmx
    nodePort: 31199
    port: 7199
  selector:
    app: cassandra
