---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: asset-mgr-ms
  name: asset-mgr-ms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: asset-mgr-ms
    spec:
      containers:
      - image: ibmcase/asset-mgr-ms
        imagePullPolicy: IfNotPresent
        name: asset-mgr-ms
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: asset-mgr-ms-cm
  labels:
    chart: asset-mgr-ms
data:
  conf/config.properties: /
    cassandra.contactpoints=localhost
    cassandra.port=9042
    cassandra.keyspace=assetmonitoring
    cassandra.asset.table.name=assets
    cassandra.strategy=SimpleStrategy
    cassandra.replicas=1
    kafka.bootstrap.server=docker.for.mac.host.internal:30092
    kafka.asset.topic.name=asset-topic
    kafka.groupid=assetinjectors
    kafka.poll.duration=2000
---
apiVersion: v1
kind: Service
metadata:
  name: asset-mgr-ms-svc
  labels:
    chart: asset-mgr-ms
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: asset-mgr-ms-svc
  selector:
    app: asset-mgr-ms
