---
apiVersion: v1
kind: Service
metadata:
  name: asset-mgr-ms
  labels:
    app: asset-mgr-ms
spec:
  type: NodePort
  selector:
    app: asset-mgr-ms
  ports:
  - protocol: TCP
    port: 8080
    name: http
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: asset-mgr-ms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: asset-mgr-ms
    spec:
      containers:
      - name: asset-mgr-ms
        image: ibmcase/asset-mgr-ms:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1

